[workspace]
members = ["packages/cjdev", "packages/yacli", "packages/yadi"]
build-members = []
test-members = []
compile-option = ""
override-compile-option = "-Woff unused"
link-option = ""
target-dir = ""

[dependencies]
