[workspace]
members = ["cjdev", "libs/yacli", "libs/yadi"]
build-members = []
test-members = []
compile-option = ""
override-compile-option = "-Woff unused"
link-option = ""
target-dir = ""

[dependencies]
