[package]
cjc-version = "1.0.5"
name = "cjdev"
description = "nothing here"
version = "0.1.0"
target-dir = ""
output-type = "executable"
compile-option = ""
override-compile-option = "-Woff unused"
link-option = ""
package-configuration = {}

[target.x86_64-unknown-linux-gnu]
[target.x86_64-unknown-linux-gnu.bin-dependencies]
path-option = ["${CANGJIE_STDX_PATH}"]

[dependencies]
cangjie_toml = { git = "https://gitcode.com/filaco/cangjie_toml", branch = "main" }
registry = { git = "https://github.com/FilaCo/registry-cj", branch = "master" }
