[package]
cjc-version = "1.0.5"
name = "cjdev"
description = "nothing here"
version = "1.0.0"
target-dir = ""
output-type = "executable"
compile-option = ""
override-compile-option = ""
link-option = ""
package-configuration = {}

[target.x86_64-unknown-linux-gnu]
[target.x86_64-unknown-linux-gnu.bin-dependencies]
path-option = ["${CANGJIE_STDX_PATH}"]

[dependencies]
cli = { git = "https://gitcode.com/filaco/cli-cj", branch = "main" }
cangjie_toml = { git = "https://gitcode.com/filaco/cangjie_toml", branch = "main" }
yadi = { path = "../yadi" }
